### ISSUE TITLE
Some Coins Gone

### ISSUE THREAD

**Issue by RyanF109** [Cybourgeoisie/cryptofolio#2]
Yesterday some coins disappeared from my available options to trade.

At the same time, my balance was showing sometimes "" and sometimes a ridiculously large number in the billions.

To resolve this I cleared cookies and history, and removed the coins no longer listed from the backup data. These include District0x and Musicoin.

**Comment by MSFTserver** [comment]
this most likely it only calling the main api wich only displays the first 100 coins i changed mine to 250 wich seems to brought back district0x and seems musicoin is rank 304 so thats why they fell off your charts

**Comment by RyanF109** [comment]
I can't seem to find the variable set to 100, can you advise what it's called?

**Comment by RyanF109** [comment]
I found it. Line 1849 in index.html at time of posting.

`$.getJSON('https://api.coinmarketcap.com/v1/ticker/', function(data) {`

Changed to:

`$.getJSON('https://api.coinmarketcap.com/v1/ticker/?limit=10000', function(data) {`

**Comment by RyanF109** [comment]
I did try and add this to settings and send a pull request but my java skills will need some improvement first! Will try and do this.

**Comment by MSFTserver** [comment]
got it covered no worries 👍

**Comment by RyanF109** [comment]
I look forward to seeing how this is done. Many thanks .
