### ISSUE TITLE
how would someone set up a site like this?

### ISSUE THREAD

**Issue by MSFTserver** [Cybourgeoisie/cryptofolio#3]
everything works till comes down to the api that is not included was wondering if i could get my hands on it or atleast release it under the MIT license please

**Comment by Cybourgeoisie** [comment]
I'll provide the API and backend soon. I didn't include it originally since it seemed to be an unpopular feature, but I wanted it for my own benefit (I like to log into my profile from various devices to update the portfolio / see how it's doing).

**Comment by MSFTserver** [comment]
sweet! :+1:

**Comment by mhn-mnsr** [comment]
Is there a way to choose what exchange to pull rates from?

**Comment by hoshsadiq** [comment]
@Cybourgeoisie any updates on the API and backend?

**Comment by Nerijusvinyl** [comment]
API is definitely needed!

**Comment by Cybourgeoisie** [comment]
Done! My apologies for the delay, I was away for the past two weeks. The backend is pushed separately to https://github.com/Cybourgeoisie/10KPizza, which includes a link to this repository.

I've included a detailed set of installation and usage instructions to the README, and I'm pretty sure I've collected everything, but please let me know if I left anything out.

**Comment by hoshsadiq** [comment]
Thank you!
