### ISSUE TITLE
Opus Token OPT missing

### ISSUE THREAD

**Issue by imp1sh** [Cybourgeoisie/cryptofolio#4]
Hi,

can't find the Opus Token. Can you please add it?

Thank you

**Comment by MSFTserver** [comment]
this related it pulling the first 100 coins would need to change the api link to pull the amount youd want

**Comment by MSFTserver** [comment]
refer here for the fix https://github.com/Cybourgeoisie/cryptofolio/issues/2 ill probably be making a pr to fix it soon

**Comment by MSFTserver** [comment]
https://github.com/Cybourgeoisie/cryptofolio/pull/5

**Comment by Cybourgeoisie** [comment]
Thanks MSFTserver! I apologize for not responding sooner - I didn't see this until now.
