### ISSUE TITLE
Alternative currencies returning dollar value

### ISSUE THREAD

**Issue by RyanF109** [Cybourgeoisie/cryptofolio#8]
Alternative currencies are now returning the value of dollar.

**Comment by hyttra** [comment]
Agreed, Please can you fix this issue?

I love this portfolio, its very simple.  I just hope you can fix these obvious bugs so it can be accurate and usable.

**Comment by RyanF109** [comment]
This issue is now fixed.

**Comment by hyttra** [comment]
How exactly is this fixed if its still returning the dollar value when setting it to EUR ??
Go to https://www.10k.pizza/ and see for yourself.

The last commit was done 6 November 2018, and you said that this was magically fixed on 12 January 2019?
